TESTS += \
	unit_tests/aggregation/test-aggregation \
	unit_tests/aggregation/test-mon \
	unit_tests/aggregation/test-normalization \
	unit_tests/aggregation/test-pruning \
	unit_tests/aggregation/test-segregation \
